#!/usr/bin/env node
// Regenerates CATALOG.md from every installed skill directory.
// Usage: node scripts/build-catalog.mjs [extraRoot ...]

import { readdirSync, readFileSync, realpathSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HOME = homedir();
const SKILL_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_ROOTS = [
  join(HOME, ".agents/skills"),
  join(HOME, ".claude/skills"),
  join(HOME, ".pi/agent/skills"),
];
const MAX_DEPTH = 4;
const DESC_LIMIT = 260;

const roots = [...DEFAULT_ROOTS, ...process.argv.slice(2).map((p) => resolve(p))];

function findSkillFiles(dir, depth = 0) {
  if (depth > MAX_DEPTH) return [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  const found = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.name === "SKILL.md" && !entry.isDirectory()) {
      found.push(full);
      continue;
    }
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
    let isDir = entry.isDirectory();
    if (entry.isSymbolicLink()) {
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        isDir = false;
      }
    }
    if (isDir) found.push(...findSkillFiles(full, depth + 1));
  }
  return found;
}

function parseFrontmatter(text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!match) return {};
  const fields = {};
  let key = null;
  for (const line of match[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/.exec(line);
    if (kv) {
      key = kv[1];
      fields[key] = kv[2].trim();
    } else if (key && /^\s+\S/.test(line)) {
      fields[key] = `${fields[key]} ${line.trim()}`.trim();
    }
  }
  for (const k of Object.keys(fields)) {
    fields[k] = fields[k].replace(/^["']|["']$/g, "");
  }
  return fields;
}

// First column of a markdown table, when it holds a backticked command.
function parseCommands(text) {
  const commands = [];
  for (const line of text.split(/\r?\n/)) {
    const cell = /^\|\s*`([^`]+)`\s*\|/.exec(line);
    if (!cell) continue;
    const name = cell[1].trim().split(/[\s[]/)[0];
    if (name && !commands.includes(name)) commands.push(name);
  }
  return commands;
}

// Keyed by name, not path: the same skill is copied or symlinked into many
// harness directories, and the user only ever types the name.
const skills = new Map();
const seenPaths = new Set();
for (const root of roots) {
  for (const file of findSkillFiles(root)) {
    let real;
    try {
      real = realpathSync(file);
    } catch {
      continue;
    }
    if (seenPaths.has(real)) continue;
    seenPaths.add(real);
    let text;
    try {
      text = readFileSync(file, "utf8");
    } catch {
      continue;
    }
    const fm = parseFrontmatter(text);
    if (!fm.name || !fm.description) continue;
    const path = real.replace(HOME, "~");
    const existing = skills.get(fm.name);
    if (existing) {
      existing.paths.push(path);
      for (const cmd of parseCommands(text)) {
        if (!existing.commands.includes(cmd)) existing.commands.push(cmd);
      }
      continue;
    }
    skills.set(fm.name, {
      name: fm.name,
      description: fm.description,
      commands: parseCommands(text),
      paths: [path],
      hidden: String(fm["disable-model-invocation"]).toLowerCase() === "true",
    });
  }
}

const sorted = [...skills.values()].sort((a, b) => a.name.localeCompare(b.name));
const lines = [
  "# Catalog",
  "",
  `Generated by \`node ${relative(SKILL_DIR, fileURLToPath(import.meta.url))}\`. Do not edit by hand.`,
  "",
  `${sorted.length} skills. "Use when" is the skill's own trigger description, truncated. Commands are the sub-commands its SKILL.md documents; read that file before naming one in a prompt.`,
  "",
];

for (const skill of sorted) {
  const desc = skill.description.length > DESC_LIMIT
    ? `${skill.description.slice(0, DESC_LIMIT).replace(/\s+\S*$/, "")}…`
    : skill.description;
  lines.push(`## ${skill.name}${skill.hidden ? " (manual only)" : ""}`);
  lines.push(`- Use when: ${desc}`);
  if (skill.commands.length) {
    lines.push(`- Commands (${skill.commands.length}): ${skill.commands.join(", ")}`);
  }
  lines.push(`- File: ${skill.paths[0]}${skill.paths.length > 1 ? ` (+${skill.paths.length - 1} copy)` : ""}`);
  lines.push("");
}

const out = join(SKILL_DIR, "CATALOG.md");
writeFileSync(out, `${lines.join("\n").trimEnd()}\n`);
console.log(`Wrote ${out} (${sorted.length} skills)`);
